# Generated by Django 4.1.3 on 2022-12-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bluesea", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="ip",
            field=models.TextField(max_length=45),
        ),
        migrations.AlterField(
            model_name="author",
            name="port",
            field=models.IntegerField(),
        ),
    ]
